
/*
 *		This was generated by opening the company database
 *		Programmability -> Stored Procedures, Right-Click
 *		"Stored Procedures" folder and select "New Stored Procedure..."
 *
 *		



SELECT * FROM tblEdPoDetail
select * from tblArShipTo

select * from trav_tblArShipTo_view

select * from tblEdPartner
select * from tblArCust where CustId LIKE '%AUT%'


----------------------------------------------------------------
select * from tblEdPoHeadeR
select * from tblEdPoDetail

select * from tblEdPartner
update tblEdPartner set DfltCustID = 'AUTOZN'

select * from trav_tblArShipTo_view where custid='AUTOZN'
and cf_EDIShipToCode='3947'
----------------------------------------------------------------



 *
 */
 
USE [EDI]
-- ================================================
-- Template generated from Template Explorer using:
-- Create Procedure (New Menu).SQL
--
-- Use the Specify Values for Template Parameters 
-- command (Ctrl-Shift-M) to fill in the parameter 
-- values below.
--
-- This block of comments will not be included in
-- the definition of the procedure.
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
--CREATE PROCEDURE <Procedure_Name, sysname, rptEdPoDtlImportLog_sp>
CREATE PROCEDURE dbo.rptEdPoDtlImportLog_sp 
	-- Add the parameters for the stored procedure here
	--<@Param1, sysname, @p1> <Datatype_For_Param1, , int> = <Default_Value_For_Param1, , 0>, 
	--<@Param2, sysname, @p2> <Datatype_For_Param2, , int> = <Default_Value_For_Param2, , 0>
	@PostRun varchar(50)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	--SELECT <@Param1, sysname, @p1>, <@Param2, sysname, @p2>
	
	SELECT h.ImportBatchId, h.PartnerID, p.PartnerName, h.CustPoNum, h.TypeCode, h.DepartmentID,     d.ItemId   ,d.polinenum,st.ShipToName,      
	case when isdate(h.PoDate) = 0 then null else case ltrim(rtrim(h.PoDate))  when '' then null   else    cast(h.PoDate as datetime)   end           end PoDate,            
	          
	case when isdate(h.StartShipDate) = 0 then null else          
	          
	 case ltrim(rtrim(h.StartShipDate))           
	  when '' then null          
	 else          
	  cast(StartShipDate as datetime)          
	 end           
	end StartShipDate,          
	case when isdate(h.CancelShipDate) = 0 then null else          
	           
	 case ltrim(rtrim(h.cancelShipDate))           
	  when '' then null          
	 else          
	  cast(CancelShipDate as datetime)          
	 end           
	End CancelShipDate,  
	'' ShipNotBeforeDate,        
	d.StoreNum,          
	d.ItemUpc,           
	cast(isnull(d.QtyOrd,0) as float) QtyOrd,          
	d.UnitsSell,           
	cast (isnull(d.UnitPrice,0) as float) UnitPrice,           
	(cast(isnull(d.UnitPrice,0) as float) * cast(isnull(d.QtyOrd,0) as float)) ExtPrice,          
	d.ColorDescr, d.SizeDescr, d.ItemDecr,          
	cast (isnull(d.RetailPrice,0)  as float) RetailPrice,          
	(cast(isnull(d.retailPrice,0) as float) * cast(isnull(d.QtyOrd,0) as float))  ExtRetailPrice          
	, h.ReqAcknlYN, h.PoStatus , S.Descr as PoStatusDesc-- csi sc 09/27/07  
	, d.ItemBuyerCode , d.ItemVendorCode
	      
	from dbo.tblEdPoHeader h            
	left join dbo.tblEdPoDetail d on h.PartnerId = d.PartnerID and h.CustPoNum = d.CustPoNum   and h.ImportBatchId = d.ImportBatchId           
	left join dbo.tblEdPartner p on h.PartnerID = p.PartnerID
	--left join dbo.tblArShipTo st ON p.CustId=st.CustiD and d.storenum=st.EdiShiptoCode
	left join dbo.trav_tblArShipTo_view st ON p.DfltCustID=st.CustiD and d.storenum=st.cf_EDIShipToCode
	--left join dbo.tblInItemUom u ON d.UnitsSell=u.Uom AND d.ItemId=u.ItemId
	left join dbo.tblEdPoStatus S on h.PoStatus = S.PoStatus
	where  (@PostRun='') OR (@PostRun=h.ImportBatchId )


	--select * from tblarshipto      
	--select * from tbledpoheader
	
END
GO








