RESTORE FILELISTONLY
FROM DISK = 'G:\Backups\SYS 050811.BAK'

RESTORE DATABASE SYS
   FROM DISK = 'G:\Backups\SYS 050811.BAK'
   WITH NORECOVERY,
   MOVE 'SYS' TO 'D:\SQLData\Boca\SYS.mdf', 
   MOVE 'SYS_LOG' TO 'D:\SQLData\Boca\SYS_log.ldf'


RESTORE FILELISTONLY
FROM DISK = 'G:\Backups\ST 050811.BAK'

RESTORE DATABASE ST
   FROM DISK = 'G:\Backups\ST 050811.BAK'
   WITH NORECOVERY,
   MOVE 'ST' TO 'D:\SQLData\Boca\ST.mdf', 
   MOVE 'ST_LOG' TO 'D:\SQLData\Boca\ST_log.ldf'


