
BACKUP DATABASE SYS
   TO DISK = 'C:\SYSBAK.BAK'

RESTORE DATABASE SYS_1
   FROM DISK = 'C:\SYSBAK.BAK'
   WITH REPLACE,
   MOVE 'SYS' TO 'S:\SQL Data\Traverse\SYS_1_Data.MDF', 
   MOVE 'SYS_LOG' TO 'S:\SQL Data\Traverse\SYS_1_Log.LDF'
GO


